### ISSUE TITLE
Remove semicolons

### ISSUE THREAD

**Issue by stefandesu** [Bamblehorse/tiny#2]
Hi,

I loved your article! 

You could remove the three semicolons to make it even tinier. Who needs those anyway. 🤷‍♂️

(Feel free to close this if you don't agree. I just had a funny moment. 🙈)

**Comment by Bamblehorse** [comment]
Thank you for your feedback 🙂 

I believe it is of paramount importance to always consider tinier and tinier alternatives 😉

**Comment by jerbear2008** [comment]
#4 actually does this. My PRs #5 and #6 make this really small.

**Comment by Bamblehorse** [comment]
Thanks for the contributions but will be leaving it as is to stay consistent with the article 🙂
